### ISSUE TITLE
Undefined array key & IdentifierNotFound errors

### ISSUE THREAD

**Issue by jakublabno** [okapi-web/php-aop#21]
I've encountered this problem, what's the reason for that?

```
PHP Fatal error:  Uncaught ErrorException: Undefined array key "Kohana\StackTrace" in /app/application/lib/okapi/aop/src/Core/Matcher/AspectMatcher.php:109
Stack trace:
#0 /app/application/lib/okapi/aop/src/Core/Matcher/AspectMatcher.php(109): Kohana_Core::error_handler()
#1 /app/application/lib/okapi/aop/src/Core/AutoloadInterceptor/ClassLoader.php(71): Okapi\Aop\Core\Matcher\AspectMatcher->matchByClassLoader()
#2 /app/application/lib/okapi/code-transformer/src/Core/AutoloadInterceptor/ClassLoader.php(68): Okapi\Aop\Core\AutoloadInterceptor\ClassLoader->findFile()
#3 /app/application/lib/kohana-module/system/kohana/classes/kohana/core.php(1112): Okapi\CodeTransformer\Core\AutoloadInterceptor\ClassLoader->loadClass()
#4 /app/application/lib/kohana-module/system/kohana/classes/kohana/core.php(1066): Kohana_Core::debug_path()
#5 /app/application/lib/kohana-module/system/kohana/classes/kohana/core.php(974): Kohana_Core::exception_text()
#6 [internal function]: Kohana_Core::exception_handler()
#7 {main}
  thrown in /app/application/lib/okapi/aop/src/Core/Matcher/AspectMatcher.php on line 109
255

Process finished with exit code 255

```

**Comment by WalterWoshid** [comment]
Hi @jakublabno,

could you create a small demo of your `kernel`, `aspect` and `target class`, so I can replicate it?

I think I know where the issue is, but I'd like to test it for myself

**Comment by WalterWoshid** [comment]
Hi @jakublabno,

I have fixed the error. It seems like accessing an array that does not have a key, prints a warning. And from your stacktrace I can see that your application has a custom error handler, which can convert a warning to an exception, check out version `1.2.1` :)

**Comment by jakublabno** [comment]
There is another error, also similar was with #[AllowDynamicProperties]
```
Roave\BetterReflection\Reflector\Exception\IdentifierNotFound [ 0 ]: Roave\BetterReflection\Reflection\ReflectionClass "JetBrains\PhpStorm\Deprecated" could not be found in the located source ~ DOCROOT/application/lib/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php [ 26 ]
```

**Comment by WalterWoshid** [comment]
Hi @jakublabno,

Seems like attributes like `JetBrains\PhpStorm` are not actually stored in the project, but the IDE itself. I have added a test case for that and also fixed it by ignoring attributes that can't be reflected, check out version `1.2.2` :)
